// ========================= REGAME LEVEL =========================
// Generated + user-safe regions for Cursor/Codegen

/* <<<AUTO-GENERATED:IMPORTS:START>>> */
// No components used yet
/* <<<AUTO-GENERATED:IMPORTS:END>>> */

/* <<<USER-IMPORTS:START>>> */
// Add your own imports below. These will NOT be overwritten.
/* <<<USER-IMPORTS:END>>> */

export function MainScene(ctx) {
  /* <<<AUTO-GENERATED:SCENE:START>>> */
  // Add GameObjects using the editor!
  /* <<<AUTO-GENERATED:SCENE:END>>> */

  /* <<<USER-CODE:SCENE:START>>> */
  // Add custom scene logic here (persisted across regenerations)
  /* <<<USER-CODE:SCENE:END>>> */
}

