import { useState } from 'react';
import type { EditorMode, Project } from '../types';
import './Toolbar.css';

interface ToolbarProps {
  project: Project;
  projectPath?: string;
  mode: EditorMode;
  onModeChange: (mode: EditorMode) => void;
  onProjectClose: () => void;
  onRun?: (platform: 'start' | 'android' | 'ios' | 'web') => void;
  onSave?: () => void;
}

export function Toolbar({ project, projectPath, mode, onModeChange, onProjectClose, onRun, onSave }: ToolbarProps) {
  const [showRunDropdown, setShowRunDropdown] = useState(false);
  
  const handleExport = () => {
    const code = generateGameCode(project);
    navigator.clipboard.writeText(code);
    alert('✅ Code copied to clipboard!');
  };

  const handleRun = (platform: 'start' | 'android' | 'ios' | 'web') => {
    setShowRunDropdown(false);
    if (onRun) {
      onRun(platform);
    }
  };

  const hasActualProject = projectPath && projectPath !== '';

  return (
    <div className="toolbar">
      <div className="toolbar-left">
        <button className="toolbar-btn" onClick={onProjectClose}>
          ← Projects
        </button>
        <span className="toolbar-project-name">{project.name}</span>
        {projectPath && (
          <span className="toolbar-project-path">📁 {projectPath}</span>
        )}
      </div>

      <div className="toolbar-center">
        {hasActualProject ? (
          <>
            {onSave && (
              <button 
                className="toolbar-control-btn"
                onClick={onSave}
                title="Save changes to App.js"
              >
                💾 Save
              </button>
            )}
            
            <div className="toolbar-run-dropdown">
              <button 
                className="toolbar-control-btn toolbar-run-btn"
                onClick={() => setShowRunDropdown(!showRunDropdown)}
              >
                ▶ Run
              </button>
              {showRunDropdown && (
                <div className="toolbar-dropdown-menu">
                  <button onClick={() => handleRun('start')}>
                    📱 Start Server
                  </button>
                  <button onClick={() => handleRun('android')}>
                    🤖 Android
                  </button>
                  <button onClick={() => handleRun('ios')}>
                    🍎 iOS
                  </button>
                  <button onClick={() => handleRun('web')}>
                    🌐 Web
                  </button>
                </div>
              )}
            </div>
          </>
        ) : (
          <span className="toolbar-info">Design-only mode</span>
        )}
      </div>

      <div className="toolbar-right">
        <button className="toolbar-btn" onClick={handleExport}>
          ▶️ Export Code
        </button>
      </div>
    </div>
  );
}

function generateGameCode(project: Project): string {
  const { scene } = project;
  
  let code = `// Generated by ReGame Engine Editor
import { Game, pos, rect, circle, color, body, area } from "../engine";

export default function ${sanitizeName(project.name)}() {
  return (
    <Game showGamePad>
      {(ctx) => {
`;

  scene.objects.forEach(obj => {
    const components = [`pos(${obj.transform.x}, ${obj.transform.y})`];
    
    const shapeComp = obj.components.find(c => c.type === obj.type);
    if (obj.type === 'rect' && shapeComp) {
      const { width, height, color: objColor } = shapeComp.properties;
      components.push(`rect(${width}, ${height}, '${objColor}')`);
    } else if (obj.type === 'circle' && shapeComp) {
      const { radius, color: objColor } = shapeComp.properties;
      components.push(`circle(${radius}, '${objColor}')`);
    }
    
    if (obj.tags.length > 0) {
      obj.tags.forEach(tag => components.push(`"${tag}"`));
    }
    
    code += `        const ${sanitizeVarName(obj.name)} = ctx.add([
          ${components.join(',\n          ')}
        ]);

`;
  });

  code += `        // Add your game logic here
      }}
    </Game>
  );
}`;

  return code;
}

function sanitizeName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '') || 'Game';
}

function sanitizeVarName(name: string): string {
  return name.toLowerCase().replace(/[^a-zA-Z0-9]/g, '_') || 'object';
}

